#!/bin/sh
# --- SDE-COPYRIGHT-NOTE-BEGIN ---
# This copyright note is auto-generated by ./scripts/Create-CopyPatch.
#
# Filename: package/.../sde-debug/test_shares.sh
# Copyright (C) 2007 The OpenSDE Project
# Copyright (C) 2004 - 2006 The T2 SDE Project
# Copyright (C) 1998 - 2003 Clifford Wolf
#
# More information can be found in the files COPYING and README.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License. A copy of the
# GNU General Public License can be found in the file COPYING.
# --- SDE-COPYRIGHT-NOTE-END ---
#
# List all filenames which are assigned to multiple packages in the
# package database files /var/adm/flists/*
#
# Output format:
# Package1 <Tab> Package2 <Tab> Filename
# ...

sort +1 /var/adm/flists/* | sed 's, ,|,' | \
awk 'BEGIN { FS="|"; last=""; lastpkg=""; } $2==last { print lastpkg, $1, $2; }
{ lastpkg=$1; last=$2; }' | sed 's,: ,	,g'

exit 0
