# --- SDE-COPYRIGHT-NOTE-BEGIN ---
# This copyright note is auto-generated by ./scripts/Create-CopyPatch.
#
# Filename: package/.../l7-filter/kernel.conf.sh
# Copyright (C) 2006 The OpenSDE Project
#
# More information can be found in the files COPYING and README.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License. A copy of the
# GNU General Public License can be found in the file COPYING.
# --- SDE-COPYRIGHT-NOTE-END ---

for x in CONFIG_IP_NF_CT_ACCT=y CONFIG_IP_NF_MATCH_LAYER7=m; do
	if grep -q ${x%=*} "$1"; then
		 sed -i -e "s,^.*${x%=*}.*,$x," "$1"
	else
		echo "$x" >> "$1"
	fi
done
