#!/bin/sh
# --- SDE-COPYRIGHT-NOTE-BEGIN ---
# This copyright note is auto-generated by ./scripts/Create-CopyPatch.
# 
# Filename: package/.../udev/scripts/cdsymlink_helper.sh
# Copyright (C) 2006 The OpenSDE Project
# 
# More information can be found in the files COPYING and README.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License. A copy of the
# GNU General Public License can be found in the file COPYING.
# --- SDE-COPYRIGHT-NOTE-END ---

########################################################################
#
# Description : cdsymlink_helper.sh
#
# Authors     : Jim Gifford
#
# Version     : 00.00
#
# Notes       :
#
########################################################################

. /lib/udev/helper.functions
. /etc/sysconfig/udev_helper

KERN_NAME="$1"
BUS="$2"
test=0

if [ "$KERN_NAME" = "" ]; then
	mesg Bad invocation: \$1 is not set
	exit 1
fi

if [ "$BUS" = "ide" ]; then
	FILES="`ls /sys/bus/ide/drivers/ide-cdrom | grep '\.' `"
		for file in $FILES; do
			TEST="`ls /sys/bus/ide/drivers/ide-cdrom/$file | grep -c $KERN_NAME`"
			if [ "$TEST" = "1" ]; then
				link="`echo $file | cut -f2 -d.`"
				while [ $test -lt 1 ] ; do
					if [ -e /dev/cdrom$link ]; then
						link=$[$link+1]
					else
						test=1
						echo $link
					fi
				done
			fi
		done
fi

if [ "$BUS" = "scsi" ]; then
	link=$KERN_NAME
		while [ $test -lt 1 ] ; do
			if [ -e /dev/cdrom$link ]; then
				link=$[$link+1]
			else
				test=1
				echo $link
			fi
		done
fi

