#!/bin/sh
# --- SDE-COPYRIGHT-NOTE-BEGIN ---
# This copyright note is auto-generated by ./scripts/Create-CopyPatch.
# 
# Filename: package/.../udev/scripts/load_floppy_module.sh
# Copyright (C) 2006 The OpenSDE Project
# 
# More information can be found in the files COPYING and README.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License. A copy of the
# GNU General Public License can be found in the file COPYING.
# --- SDE-COPYRIGHT-NOTE-END ---

########################################################################
#
# Description : load_floppy_module
#
# Authors     : Based on Open Suse Udev Rules
#               kay.sievers@suse.de
#
# Adapted to  : Jim Gifford
# LFS
#
# Version     : 00.00
#
# Notes       : Loads the floppy module based upon contents of the NVRAM
# 
########################################################################

PROC=/proc/driver/nvram

# wait for /proc file to appear
loop=10
while ! test -e $PROC; do
    sleep 0.1;
    test "$loop" -gt 0 || break
    loop=$(($loop - 1))
done

if [ ! -r /proc/driver/nvram ]; then
    exit 0;
fi

floppy_devices=$(cat $PROC | sed -n '/Floppy.*\..*/p')

if [ -n "$floppy_devices" ]; then
    /sbin/modprobe block-major-2
else
    /bin/true
fi

exit $?
