# --- SDE-COPYRIGHT-NOTE-BEGIN ---
# This copyright note is auto-generated by ./scripts/Create-CopyPatch.
#
# Filename: package/.../bashcompletion/profile_d_bashcomp.sh
# Copyright (C) 2004 - 2006 The T2 SDE Project
# Copyright (C) 1998 - 2004 Clifford Wolf
#
# More information can be found in the files COPYING and README.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License. A copy of the
# GNU General Public License can be found in the file COPYING.
# --- SDE-COPYRIGHT-NOTE-END ---

# off ..... just default tab completion
# intern .. smart tab completion with shell function (fast)
# extern .. smart tab completion with ext. progs (slow but cleaner)
#
completion_mode=off

if [ -n "$PS1" ]
then
	case "$completion_mode" in
	  intern)
		source /etc/bash_completion
		;;
	  extern)
		shopt -s extglob progcomp
		eval "$( bashcomp )"
		;;
	esac
fi

unset completion_mode

