#!/bin/sh
# --- SDE-COPYRIGHT-NOTE-BEGIN ---
# This copyright note is auto-generated by ./scripts/Create-CopyPatch.
#
# Filename: package/.../update.sh
# Copyright (C) 2008 The OpenSDE Project
#
# More information can be found in the files COPYING and README.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License. A copy of the
# GNU General Public License can be found in the file COPYING.
# --- SDE-COPYRIGHT-NOTE-END ---

URL="http://www.x.org/wiki/Releases/7.3"

curl "$URL" | sed -e 's,\(<a \),\n\1,g' -e 's,\(</a>\),\1\n,g' |
		sed -n -e 's,.*/xorg-announce/.*>\(.*\)<.*,\1,p' |
		grep -v CVE |
while read pkg ver; do
	sde up pkg $pkg $ver
done
